FROM alpine:3.16.0

RUN apk add --no-cache ffmpeg
RUN apk add --no-cache imagemagick
RUN apk add --no-cache openjdk17-jre-headless
RUN apk add --no-cache ttf-liberation

RUN mkdir /app
RUN mkdir /app/work
WORKDIR /app
